### ISSUE TITLE
Constraint에서 Position Constraint부분을 읽고있는데 질문있습니다.

### ISSUE THREAD

**Issue by Jiryeong29** [Jiryeong29/2023-Unity-Study#5]
```csharp
일련의 게임 오브젝트를 제약할 수 있습니다.
 예를 들어 아기 오리들이 엄마 오리를 일렬로 따라가게 하려면
 포지션 제약(Position Constraint) 컴포넌트를 Duckling1 게임 오브젝트에 추가합니다. 
소스(Sources) 리스트에서 MotherDuck 에 연결합니다. 
그런 다음, 포지션 제약 을 Duckling1 에 연결되는 Duckling2 에 추가합니다. 
MotherDuck 게임 오브젝트가 씬에서 이동하면
 Duckling1 이 MotherDuck 을 따라가고 Duckling2 가 Duckling1 을 따라갑니다.
```
[해당내용링크](https://docs.unity3d.com/kr/2019.4/Manual/Constraints.html)

[해당내용링크]에 해당하는 위의 문장을 읽고 player를 다른 오브젝트가 똘마니처럼 따라가게 하고 싶어서, 똘마니오브젝트를 추가하여 그 오브젝트에 positionConstraint 컴포넌트를 추가 해 준뒤 소스 리스트에  Player를 추가해줬습니다. 그러나 똘마니 오브젝트는 player를 따라가지 않네요. 혹시 똘마니 오브젝트에 다른 움직임동작을 넣어주는 스크립트를 짜주지 않아서 그럴까요? 위와 같은 방법을 써서 똘마니 오브젝트가 Player를 따라가게 하는 기능을 추가해주는 방법을 알고 싶습니다 !

**Comment by 1829122** [comment]
active활성화해보세요

**Comment by Jiryeong29** [comment]
헐 isactive아까 해줬을때는 안됐는데 다시 해보니까 되네요?

**Comment by Jiryeong29** [comment]
ㅎ..ㅎ 감사합니당

**Comment by Jiryeong29** [comment]
이걸로 멋진 똘마니 친구를 만들 수 있겠어요ㅎㅎ
